name: Continuous Integration

docker-check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false