name: Discord Alerts
 
on:
  push:
    branches:
      - main
 
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"Novo push na branch main por ${{ github.actor }}.\nRepositório: ${{ github.repository }}\nCommit: ${{ github.event.head_commit.message }}\"}" \
            $DISCORD_WEBHOOK
 