name: Discord Alerts

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          MESSAGE="Novo push na branch main por ${{ github.actor }}. Repositorio: ${{ github.repository }}."
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"$MESSAGE\"}" \
            $DISCORD_WEBHOOK